# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [3]:
import numpy as np

# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [4]:
arr=np.random.randint(1,21,size=(5,5))
print("OG array \n",arr)

OG array 
 [[ 1 15 18 13  9]
 [17  4 17  3  4]
 [12  6 19 14  2]
 [12  4 19  8 13]
 [11 18  9  4  7]]


In [5]:
arr[:,2]=1#you can use slicing in one of the fileds (rows or columns) and a direct value for the other
arr

array([[ 1, 15,  1, 13,  9],
       [17,  4,  1,  3,  4],
       [12,  6,  1, 14,  2],
       [12,  4,  1,  8, 13],
       [11, 18,  1,  4,  7]])

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [6]:
arr=np.arange(1,17).reshape((4,4))
print("OG array \n",arr)

OG array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [7]:
# to fill the diagonal elements 
np.fill_diagonal(arr,0)#inplace changes
arr

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [8]:
arr=np.arange(1,37).reshape(6,6);

print("OG array \n",arr)

OG array 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [9]:
arr[3:6,2:5]

array([[21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])

2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [10]:
arr=np.random.randint(1,21,size=(5,5))
print("OG array \n",arr)


OG array 
 [[ 5 17  9 19  2]
 [18  6 11  3  7]
 [15  2 10  5 19]
 [ 6 15 19 12 15]
 [19 11  1 17  3]]


In [11]:
borderElements=np.concatenate((arr[0,:],arr[:,-1],arr[-1,:],arr[:,0]))
print("Border elements:")
print(borderElements)

Border elements:
[ 5 17  9 19  2  2  7 19 15  3 19 11  1 17  3  5 18 15  6 19]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [12]:
arr1=np.random.randint(1,13,size=(3,4))
arr2=np.random.randint(1,13,size=(3,4))

#Return type of each is a numpy array
print("Addition :\n ",arr1+arr2)
print("Subtraction :\n ",arr1-arr2)
print("Multiplication :\n ",arr1*arr2)
print("Division:\n ",arr1/arr2)

Addition :
  [[ 4 10 19 16]
 [11 19  5 23]
 [ 9 12 15  6]]
Subtraction :
  [[ 2 -4 -5  0]
 [ 5 -1 -1  1]
 [ 1 10 -1 -4]]
Multiplication :
  [[  3  21  84  64]
 [ 24  90   6 132]
 [ 20  11  56   5]]
Division:
  [[ 3.          0.42857143  0.58333333  1.        ]
 [ 2.66666667  0.9         0.66666667  1.09090909]
 [ 1.25       11.          0.875       0.2       ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [13]:
arr=np.arange(1,17).reshape((4,4))

row_sum=np.sum(arr,axis=1)#Calculates the sum of each elements of a row ,as axis =1 means traversing horizontally
#The above is don for each of the 4 rows 

column_sum=np.sum(arr,axis=0)#Calculates the sum of each elements of a column ,as axis =0 means traversing vertically
#The above is don for each of the 4 columns

print("Row sum: \n",row_sum)
print("Column sum: \n",column_sum)

Row sum: 
 [10 26 42 58]
Column sum: 
 [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [14]:
arr=np.random.randint(1,21,size=(5,5))

print("Mean : ",np.mean(arr))
print("Median : ",np.median(arr))
print("Standard deviation : ",np.std(arr))
print("Variance : ",np.var(arr))

Mean :  9.16
Median :  10.0
Standard deviation :  5.82188972757128
Variance :  33.8944


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [15]:
arr=np.arange(1,10).reshape(3,3)

mean=np.mean(arr)
std=np.std(arr)

normalised_array=(arr-mean)/std
print("Normalised array : \n",normalised_array)

Normalised array : 
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [16]:
arr=np.random.randint(1,10,size=(3,3))
row_array=np.random.randint(1,11,size=(3,))#size does not comply with the range mentioned in the randint 
print(row_array)



[8 4 9]


In [17]:
print("Original array:")
print(arr)
print("1D array:")
print(row_array)

# Add the 1D array to each row of the 2D array using broadcasting
result = arr + row_array 
print("Resulting array:")
print(result)
#Adiing a 1D array to a 2D array is possible only if the 1D array has the same number of elements as the number of columns in the 2D array
#In that case the 1D array is added to each row of the 2D array

Original array:
[[6 7 5]
 [1 1 4]
 [7 9 1]]
1D array:
[8 4 9]
Resulting array:
[[14 11 14]
 [ 9  5 13]
 [15 13 10]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [18]:
# array=np.random.randint(44,10,size=(4,4))---> Wrong as the first argument needs to be lower than the second argument
array=np.random.randint(44,69,size=(4,4))
columnn_array=np.random.randint(10,21,size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(columnn_array)

column_array=columnn_array[:,np.newaxis]#Converts the 1D array to a 2D array with 1 column
print("The 2D converted array: \n",column_array)

ans=array-column_array
print("Resulting array: \n",ans)



Original array:
[[64 63 45 66]
 [68 50 48 46]
 [47 54 57 68]
 [66 64 47 54]]
1D array:
[12 11 20 19]
The 2D converted array: 
 [[12]
 [11]
 [20]
 [19]]
Resulting array: 
 [[52 51 33 54]
 [57 39 37 35]
 [27 34 37 48]
 [47 45 28 35]]


Let’s break it down step by step:

---

### Initial Assumption:
- **`array`**: A 2D array of shape `(m, n)`.  
- **`column_array`**: A 1D array of length `m` (number of rows in `array`).

---

### Code Breakdown:
```python
result = array - column_array[:, np.newaxis]
```

1. **`column_array[:, np.newaxis]`**:
   - `column_array` is reshaped from 1D `(m,)` to 2D `(m, 1)` using `np.newaxis`.
   - This makes `column_array` a column vector.

   **Example:**
   ```python
   column_array = np.array([1, 2, 3])  # Shape: (3,)
   column_array[:, np.newaxis]
   # Output:
   [[1],
    [2],
    [3]]  # Shape: (3, 1)
   ```

2. **Broadcasting**:
   - NumPy performs **broadcasting** during subtraction. The reshaped `column_array` (shape `(m, 1)`) is subtracted from the 2D `array` (shape `(m, n)`).
   - The single column `[1, 2, 3]` is subtracted from **each column** of `array`.

   **Example:**
   ```python
   array = np.array([[5, 6, 7],
                     [8, 9, 10],
                     [11, 12, 13]])  # Shape: (3, 3)

   column_array = np.array([1, 2, 3])  # Shape: (3,)

   result = array - column_array[:, np.newaxis]
   # Result:
   [[4, 5, 6],   # [5-1, 6-1, 7-1]
    [6, 7, 8],   # [8-2, 9-2, 10-2]
    [8, 9, 10]]  # [11-3, 12-3, 13-3]
   ```

---

### Why use `np.newaxis`?
The `np.newaxis` is necessary to ensure that the shapes of `array` and `column_array` are compatible for broadcasting:
- Without `[:, np.newaxis]`, `column_array` has shape `(m,)` and cannot be broadcast directly against a 2D array of shape `(m, n)`. 
- By reshaping to `(m, 1)`, NumPy knows to repeat the values of `column_array` across the columns of `array`.

---

### Summary:
- **`column_array[:, np.newaxis]`** reshapes `column_array` into a column vector.
- Subtracting this reshaped array from `array` applies the subtraction **row-wise**, subtracting the corresponding element of `column_array` from each column of that row in `array`.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [19]:
arr=np.arange(1,10).reshape(3,3)
print("Original array: \n",arr)

#determinant of a matrix
det=np.linalg.det(arr)
print("Determinant of the matrix: ",det)

#rank of a matrix
rank=np.linalg.matrix_rank(arr)

#inverse of a matrix
inverse=np.linalg.inv(arr)

#eigen values of a matrix
eigen_values=np.linalg.eig(arr)

Original array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant of the matrix:  -9.51619735392994e-16


### so I can say numpy is more like a package(a collection of files or folder ) which has modules(or files ) and the reason i can use some functions directly like np.sum or np.array is because they have been included in the _init_.py file ?

Yes, you're absolutely correct! Your understanding is spot-on. Let me elaborate to make it even clearer:

---

### **NumPy as a Package**
- **NumPy** is indeed a **package** in Python, meaning it's a **folder** containing multiple files and subfolders. 
- These files and subfolders define various **modules** and **submodules** that provide specific functionality.

---

### **Structure of NumPy**
- The main **`numpy`** folder (the package) contains:
  - Core modules like `core.py`, `multiarray.py`, etc.
  - Submodules like `linalg` (for linear algebra), `fft` (for Fourier transforms), `random` (for random numbers), etc.
  - A special file: **`__init__.py`**.

---

### **Role of `__init__.py`**
- The **`__init__.py`** file is executed when you import the `numpy` package.
- It defines:
  1. **What gets imported automatically** when you run `import numpy as np`.  
     - For example, `np.sum`, `np.array`, etc., are included in **`__init__.py`** so they are directly accessible.
  2. **Which submodules are loaded by default** (like `np.linalg`).
  3. **Convenient shortcuts** for commonly used features.

Think of it as a **setup file** that organizes how the package behaves when imported.

---

### **Why Some Functions Are Directly Accessible**
Functions like `np.sum` or `np.array` are directly accessible because:
1. They are part of NumPy's **core functionality**.
2. The **`__init__.py` file** ensures they are included at the top level of the package, making them easy to use.

In contrast, functions like `np.linalg.matrix_rank` are in the **`linalg` submodule**, so they must be accessed through `np.linalg`.

---

### **Example: Inspecting `__init__.py`**
If you look inside NumPy’s **`__init__.py`**, you might see something like:
```python
from .core import *
from .linalg import linalg
from .random import random
# Other imports and setups
```

This ensures:
- Core functions like `np.sum` and `np.array` are available directly.
- Submodules like `linalg` and `random` are not fully imported but are accessible using `np.linalg` or `np.random`.

---

### **Summary**
1. **NumPy is a package** (a collection of files and folders).
2. Core functions (like `np.sum`) are made accessible at the top level through **`__init__.py`**.
3. Submodules (like `linalg`) are not imported directly but can be accessed using their namespace (`np.linalg`).
4. This organization keeps the package clean and efficient, only loading more specific functionality when needed. 

---

If you'd like, I can also help you explore a specific submodule or walk you through creating your own package in Python! 😊

2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [20]:
first=np.random.randint(1,11,size=(2,3))
second=np.random.randint(11,21,size=(3,2))

print("First matrix: \n",first)
print("Second matrix: \n",second)

result=np.dot(first,second)
print("Resultant matrix: \n",result)

First matrix: 
 [[3 5 9]
 [6 3 7]]
Second matrix: 
 [[15 11]
 [20 13]
 [12 14]]
Resultant matrix: 
 [[253 224]
 [234 203]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [21]:
arr=np.random.randint(1,10,size=(3,3))

print("(1,9) array : ",arr.reshape((1,9)))

print("(9,1) array : \n",arr.reshape((9,1)))

print("Original array remains the same after the reshape fucntion: \n",arr)


(1,9) array :  [[4 7 9 2 3 7 9 3 1]]
(9,1) array : 
 [[4]
 [7]
 [9]
 [2]
 [3]
 [7]
 [9]
 [3]
 [1]]
Original array remains the same after the reshape fucntion: 
 [[4 7 9]
 [2 3 7]
 [9 3 1]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [22]:
arr=np.random.randint(1,100,size=(5,5))
print("Original array: \n",arr)

print("Flattened array: \n",arr.flatten())

print("Flattened array using ravel: \n",arr.ravel())

print("Original array remains the same after the flatten and ravel fucntion: \n",arr)

Original array: 
 [[48 69 43 85 52]
 [17 88 28 15 85]
 [ 6 61 13 44 74]
 [ 5 42 44 54 20]
 [24 23 69 77 70]]
Flattened array: 
 [48 69 43 85 52 17 88 28 15 85  6 61 13 44 74  5 42 44 54 20 24 23 69 77
 70]
Flattened array using ravel: 
 [48 69 43 85 52 17 88 28 15 85  6 61 13 44 74  5 42 44 54 20 24 23 69 77
 70]
Original array remains the same after the flatten and ravel fucntion: 
 [[48 69 43 85 52]
 [17 88 28 15 85]
 [ 6 61 13 44 74]
 [ 5 42 44 54 20]
 [24 23 69 77 70]]


### **Difference Between `flatten()` and `ravel()`**

Both `flatten()` and `ravel()` convert a multi-dimensional array into a 1D array, but they behave differently in terms of how they handle memory:

---

#### **1. `flatten()`**
- **Always creates a copy** of the original data.
- The returned array is independent of the original array.
- Any changes made to the flattened array **do not affect** the original array.

**Example:**
```python
arr = np.array([[1, 2], [3, 4]])
flattened = arr.flatten()
flattened[0] = 99

print("Flattened array:", flattened)  # [99, 2, 3, 4]
print("Original array:", arr)        # [[1, 2], [3, 4]] (unchanged)
```

---

#### **2. `ravel()`**
- Returns a **view** of the original array whenever possible (i.e., it doesn't make a copy unless necessary).
- Changes to the raveled array **may affect** the original array if it's a view.

**Example:**
```python
arr = np.array([[1, 2], [3, 4]])
raveled = arr.ravel()
raveled[0] = 99

print("Raveled array:", raveled)    # [99, 2, 3, 4]
print("Original array:", arr)      # [[99, 2], [3, 4]] (changed!)
```

---

#### **Key Difference:**
- **`flatten()`**: Always returns a new copy, so it's safer if you don't want to accidentally modify the original array.
- **`ravel()`**: Returns a view when possible, making it more memory-efficient. Use it when you're okay with potentially modifying the original data.

---

### **When to Use `np.function_name()` vs. `array.function_name()`**

#### **`np.function_name()` (Module-level function)**:
- Use it when the function applies to the array as a whole, even if it’s not a NumPy object.
- Works on lists, tuples, or other array-like objects in addition to NumPy arrays.
- Examples:
  - `np.sum(array)` → Sums all elements in the array.
  - `np.mean(array)` → Computes the mean.

**Example:**
```python
lst = [1, 2, 3, 4]
print(np.sum(lst))  # Works because np.sum operates on any array-like object
```

#### **`array.function_name()` (Method of a NumPy object)**:
- Use it when the function is specific to a NumPy array object.
- These methods are attached to NumPy arrays, so they only work on objects of type `np.ndarray`.
- Examples:
  - `array.flatten()`
  - `array.reshape()`

**Example:**
```python
arr = np.array([[1, 2], [3, 4]])
print(arr.flatten())  # Works because arr is a NumPy array
```

---

### **When to Choose Which:**
1. **Prefer `np.function_name()`** for more general-purpose operations (like sum, mean) or when working with data that might not yet be a NumPy array.
2. **Use `array.function_name()`** for array-specific operations (like reshape, flatten, or transpose), where you're sure you're working with an `np.ndarray`.

---

### **Your Code Explanation:**
```python
rr = np.random.randint(1, 100, size=(5, 5))

print("Original array: \n", rr)

print("Flattened array: \n", rr.flatten())  
# A new 1D array (copy), original remains unchanged.

print("Flattened array using ravel: \n", rr.ravel())  
# A 1D view (or copy if needed), changes to this may reflect on the original.

print("Original array remains the same after the flatten and ravel function: \n", rr)
# Confirms that `flatten()` never modifies the original array.
```

Let me know if you'd like further clarifications! 😊

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

### **Fancy Indexing in NumPy**

Fancy indexing refers to accessing elements in a NumPy array using **integer arrays**, **boolean arrays**, or other **arrays/lists of indices** instead of just using slices (`:`) or single indices. It allows for more flexible and powerful ways to select, modify, or extract specific elements from arrays.

---

### **Types of Fancy Indexing**

1. **Integer Array Indexing**:
   - Use arrays or lists of integers to specify the indices you want to access.
   - You can select multiple elements or rows/columns simultaneously.

   **Example:**
   ```python
   arr = np.array([10, 20, 30, 40, 50])
   indices = [1, 3, 4]
   result = arr[indices]
   print(result)  # Output: [20, 40, 50]
   ```

   **For 2D Arrays:**
   ```python
   arr = np.array([[1, 2], [3, 4], [5, 6]])
   rows = [0, 2]
   cols = [1, 0]
   result = arr[rows, cols]  # Selects (0, 1) and (2, 0)
   print(result)  # Output: [2, 5]
   ```

---

2. **Boolean Array Indexing**:
   - Use a boolean array (of the same shape) to filter elements.
   - Only elements corresponding to `True` values in the boolean array are selected.

   **Example:**
   ```python
   arr = np.array([10, 20, 30, 40, 50])
   mask = arr > 25  # Create a boolean mask
   result = arr[mask]
   print(result)  # Output: [30, 40, 50]
   ```

   **For 2D Arrays:**
   ```python
   arr = np.array([[1, 2], [3, 4], [5, 6]])
   mask = arr > 3
   result = arr[mask]
   print(result)  # Output: [4, 5, 6]
   ```

---

3. **Combined Indexing**:
   - You can combine fancy indexing with slicing or other forms of indexing.

   **Example:**
   ```python
   arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
   result = arr[1:, [0, 2]]  # Rows 1 to end, Columns 0 and 2
   print(result)
   # Output:
   # [[40 60]
   #  [70 90]]
   ```

---

### **Why Use Fancy Indexing?**
1. **Select Specific Elements**:
   - You can extract non-contiguous elements efficiently.
2. **Flexible Filtering**:
   - Use conditions to create masks and extract specific elements.
3. **Broadcasting with Indices**:
   - Combine arrays/lists of indices with slicing for powerful operations.

---

### **Key Notes**:
- Fancy indexing **returns a copy**, not a view of the data. This means modifying the result will **not affect the original array**.
- It's different from slicing (`:`), which creates a **view** of the original array.

**Example to Compare:**
```python
arr = np.array([10, 20, 30, 40, 50])

# Fancy Indexing
result = arr[[0, 2, 4]]
result[0] = 99
print(arr)  # Original array remains unchanged: [10, 20, 30, 40, 50]

# Slicing
slice_result = arr[1:4]
slice_result[0] = 99
print(arr)  # Original array is modified: [10, 99, 30, 40, 50]
```

---

Fancy indexing is one of NumPy's most powerful features for selecting and manipulating subsets of data. Let me know if you'd like to dive deeper into examples or advanced use cases! 😊

# Very Very Important (see next)

### **Key Notes**:
- Fancy indexing **returns a copy**, not a view of the data. This means modifying the result will **not affect the original array**.
- It's different from slicing (`:`), which creates a **view** of the original array.

**Example to Compare:**
```python
arr = np.array([10, 20, 30, 40, 50])

# Fancy Indexing
result = arr[[0, 2, 4]]
result[0] = 99
print(arr)  # Original array remains unchanged: [10, 20, 30, 40, 50]

# Slicing
slice_result = arr[1:4]
slice_result[0] = 99
print(arr)  # Original array is modified: [10, 99, 30, 40, 50]
```

---

In [25]:
import numpy as np

In [28]:
arr=np.random.randint(1,100,size=(5,5))

print("Original array: \n",arr)
# I need 4 elements so i will need to gove 4 values in rows and 4 values in columns
corners=arr[[0 ,0, -1, -1 ],[0, -1,0,-1]]#first argument-->rows, second argument-->columns
# So the indexes of the selected elements are (0,0),(0,-1),(-1,0),(-1,-1)

print("Corners of the array: \n",corners)



Original array: 
 [[95 40 40 27 21]
 [75 25 48 15 30]
 [15 78 60 69 21]
 [30 13 77 28 75]
 [88 45 25  8 86]]
Corners of the array: 
 [95 21 88 86]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [29]:
arr=np.random.randint(1,100,size=(4,4))

print("Original array: \n",arr)

# remember that using list to provide indexes will not change the original array
#But using booolean mask will change the original array
#arr[arr>10] selects all the elements greater than 10
arr[arr>10]=10
print("After replacing all elements greater than 10 with 10: \n",arr)

Original array: 
 [[15 31 37 84]
 [51 71 97 68]
 [15 94 27 76]
 [25 11 96 10]]
After replacing all elements greater than 10 with 10: 
 [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [31]:
data_type=[('name','U21'),('age','i4'),('weight','f4')]#The data type of the array is defined by the data type of the elements in the tuple
data=np.array([('Messi',38,76.32),('Ronaldo',36,78.32)],dtype=data_type)
print("Original array: \n",data)

sorted_array=np.sort(data,order='age')#sorts the array based on the age
print("Sorted array based on age: \n",sorted_array)


Original array: 
 [('Messi', 38, 76.32) ('Ronaldo', 36, 78.32)]
Sorted array based on age: 
 [('Ronaldo', 36, 78.32) ('Messi', 38, 76.32)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [34]:
data_type=[('x','i4'),('y','i4')] #'i4' means 4-byte integer
data=np.array([(0,10),(3,98),(10,50)],dtype=data_type)
print("Original array: \n",data)
print()
print(data['x'])
print(data['x'][:,np.newaxis])
print(data['x'])#original remains the same

Original array: 
 [( 0, 10) ( 3, 98) (10, 50)]

[ 0  3 10]
[[ 0]
 [ 3]
 [10]]
[ 0  3 10]


In [35]:
print(data['x'][:,np.newaxis]-data['x'])#subtracts each element of the 1D array from each row of the 2D array

[[  0  -3 -10]
 [  3   0  -7]
 [ 10   7   0]]


In [36]:
print(data['y'][:,np.newaxis]-data['y'])

[[  0 -88 -40]
 [ 88   0  48]
 [ 40 -48   0]]


In [37]:
distances = np.sqrt((data['x'][:,np.newaxis]-data['x'])**2 + (data['y'][:,np.newaxis]-data['y'])**2)#calculates the distance between each pair of points
print("Pairwise Euclidean distances: \n",distances)
#9 elements the distnac the (0,0) element is the distnace between 1st and 1nd element
#The (0,1) element is the distance between the 1st and 2nd element
#The (0,2) element is the distance between the 1st and 3rd element
# The (1,0) element is the distance between the 2nd and 1st element
# And so on 

Pairwise Euclidean distances: 
 [[ 0.         88.05112151 41.23105626]
 [88.05112151  0.         48.50773134]
 [41.23105626 48.50773134  0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

### **What is Masking in NumPy?**

**Masking** in NumPy allows you to selectively "hide" certain elements in an array by applying a **mask**. A mask is a boolean condition (or a special indicator) that marks which elements should be considered **invalid** or **ignored** during computations.

Masked arrays are implemented in the **`numpy.ma`** module, where `ma` stands for **masked array**. When elements are masked:
- They are treated as **missing** or **invalid**.
- Operations like summing, averaging, or other computations ignore the masked elements.

---

### **Your Code Explained**

```python
import numpy.ma as ma
import numpy as np

# Create a 4x4 array with random integers between 1 and 20
array = np.random.randint(1, 21, size=(4, 4))
```
- Creates a 2D array of shape `(4, 4)` with random integers between 1 and 20.

---

#### **Step 1: Applying a Mask**
```python
masked_array = ma.masked_greater(array, 10)
```
- `ma.masked_greater(array, 10)` masks all elements in `array` that are **greater than 10**.
- The mask is a boolean array of the same shape as `array`, where:
  - `True` means the element is **masked** (ignored).
  - `False` means the element is **unmasked** (valid).

**Example:**
Suppose `array` is:
```plaintext
[[ 3, 12, 15,  8],
 [ 9, 14, 10, 11],
 [ 7, 13,  6,  2],
 [16,  1,  4, 18]]
```

The masked array becomes:
```plaintext
[[ 3 -- --  8]
 [ 9 -- 10 --]
 [ 7 --  6  2]
 [--  1  4 --]]
```
Here, `--` indicates a masked element.

---

#### **Step 2: Printing the Masked Array**
When you print a masked array, the masked elements are displayed as `--` to indicate they are ignored.

```python
print("Original array:")
print(array)

print("Masked array:")
print(masked_array)
```

---

#### **Step 3: Sum of Unmasked Elements**
```python
sum_unmasked = masked_array.sum()
```
- Computes the sum of all **unmasked elements** in the masked array.
- Masked elements (`--`) are ignored during the sum.

**Example (continuing from above):**
Unmasked elements are `[3, 8, 9, 10, 7, 6, 2, 1, 4]`.
Their sum:
```plaintext
3 + 8 + 9 + 10 + 7 + 6 + 2 + 1 + 4 = 50
```

---

### **Key Features of Masking**
1. **Mask Creation**:
   - Masks can be created manually or automatically based on a condition.
   - `ma.masked_where(condition, array)` masks elements where the condition is `True`.
   - Other functions: `ma.masked_greater`, `ma.masked_less`, `ma.masked_equal`.

2. **Masked Operations**:
   - Masked elements are ignored in calculations like `sum`, `mean`, etc.
   - Works seamlessly with other NumPy operations.

3. **Underlying Data**:
   - The original data remains intact; only the mask changes how it is accessed or computed.

4. **Accessing the Mask**:
   - `masked_array.mask` gives the mask (a boolean array).
   - Example:
     ```python
     print(masked_array.mask)
     ```

5. **Filling Masked Elements**:
   - You can replace masked values with a default value using `filled()`:
     ```python
     filled_array = masked_array.filled(0)  # Replace masked elements with 0
     ```

---

### **Why Use Masking?**
- To handle **missing** or **invalid data** in computations.
- To focus only on specific elements in an array while ignoring others.
- Useful for data cleaning, statistical analysis, and preprocessing.

---

Let me know if you'd like more examples or clarifications! 😊

In [63]:
import numpy.ma as ma #ma stands for masked array

arr=np.random.randint(1,20,size=(4,4))
print("Original array: \n",arr)

masked_array=ma.masked_greater(arr,10)
print("Masked array: \n",masked_array)



Original array: 
 [[ 3 18 11  4]
 [18 14 17 12]
 [ 1 17  8  1]
 [ 3 12 19  8]]
Masked array: 
 [[3 -- -- 4]
 [-- -- -- --]
 [1 -- 8 1]
 [3 -- -- 8]]


In [64]:
print("Sum of original array",np.sum(arr))
print("Sum of masked array",np.sum(masked_array))

Sum of original array 166
Sum of masked array 28


In [65]:
masked_array.filled(0)
print("Masked array filled with 0: \n",masked_array)

Masked array filled with 0: 
 [[3 -- -- 4]
 [-- -- -- --]
 [1 -- 8 1]
 [3 -- -- 8]]


In [66]:
filled_array=masked_array.filled(0)
print("Filled array: \n",filled_array)

Filled array: 
 [[3 0 0 4]
 [0 0 0 0]
 [1 0 8 1]
 [3 0 0 8]]


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [57]:
arr=np.random.randint(1,20,size=(3,3))

print("Original array: \n",arr)
temp=np.eye(3,dtype=bool)
print("Boolean mask: \n",temp)

masked_array=ma.masked_array(arr,mask=temp)#masks the elements of the array where the mask(here temp) is True
print("Masked array: \n",masked_array)

Original array: 
 [[ 8  1  6]
 [11 13  7]
 [ 2  2  3]]
Boolean mask: 
 [[ True False False]
 [False  True False]
 [False False  True]]
Masked array: 
 [[-- 1 6]
 [11 -- 7]
 [2 2 --]]


In [58]:
masked_array=masked_array.filled(masked_array.mean())#fills the masked elements with the mean of the array
print("Filled array: \n",masked_array)

Filled array: 
 [[ 4  1  6]
 [11  4  7]
 [ 2  2  4]]
